//The list of all the player textures, both the default models and the partial textures used for customization

export interface BodyResourceDescriptionListInterface {
    [key: string]: BodyResourceDescriptionInterface
}

export interface BodyResourceDescriptionInterface {
    name: string,
    img: string
}

export const PLAYER_RESOURCES: BodyResourceDescriptionListInterface = {
    "Adam": {name: "Adam", img: "resources/characters/limezu/Adam_16x16.png"},
    "Alex": {name: "Alex", img: "resources/characters/limezu/Alex_16x16.png"},
    "Amelia": {name: "Amelia", img: "resources/characters/limezu/Amelia_16x16.png"},
    "Ash": {name: "Ash", img: "resources/characters/limezu/Ash_16x16.png"},
    "Bob": {name: "Bob", img: "resources/characters/limezu/Bob_16x16.png"},
    "Bouncer": {name: "Bouncer", img: "resources/characters/limezu/Bouncer_16x16.png"},
    "Bruce": {name: "Bruce", img: "resources/characters/limezu/Bruce_16x16.png"},
    "Cman": {name: "Cman", img: "resources/characters/limezu/Conference_man_16x16.png"},
    "Cwoman": {name: "Cwoman", img: "resources/characters/limezu/Conference_woman_16x16.png"},
    "Dan": {name: "Dan", img: "resources/characters/limezu/Dan_16x16.png"},
    "Edward": {name: "Edward", img: "resources/characters/limezu/Edward_16x16.png"},
    "Lucy": {name: "Lucy", img: "resources/characters/limezu/Lucy_16x16.png"},
    "Molly": {name: "Molly", img: "resources/characters/limezu/Molly_16x16.png"},
    "Owoman": {name: "Owoman", img: "resources/characters/limezu/Old_woman_Jenny_16x16.png"},
    "Pier": {name: "Pier", img: "resources/characters/limezu/Pier_16x16.png"},
    "Rob": {name: "Rob", img: "resources/characters/limezu/Rob_16x16.png"},
    "Roki": {name: "Roki", img: "resources/characters/limezu/Roki_16x16.png"},
    "Samuel": {name: "Samuel", img: "resources/characters/limezu/Samuel_16x16.png"},
};

export const COLOR_RESOURCES: BodyResourceDescriptionListInterface = {
    "body_1": {name: "body_1", img: "resources/customisation/limezu/Body_1.png"},
    "body_2": {name: "body_2", img: "resources/customisation/limezu/Body_2.png"},
    "body_3": {name: "body_3", img: "resources/customisation/limezu/Body_3.png"},
    "body_4": {name: "body_4", img: "resources/customisation/limezu/Body_4.png"},
};

export const EYES_RESOURCES: BodyResourceDescriptionListInterface = {
    "eyes_1": {name: "eyes_1", img: "resources/customisation/limezu/Eyes_1.png"},
    "eyes_2": {name: "eyes_2", img: "resources/customisation/limezu/Eyes_2.png"},
    "eyes_3": {name: "eyes_3", img: "resources/customisation/limezu/Eyes_3.png"},
    "eyes_4": {name: "eyes_4", img: "resources/customisation/limezu/Eyes_4.png"},
    "eyes_5": {name: "eyes_5", img: "resources/customisation/limezu/Eyes_5_horizontal.png"},
    "eyes_6": {name: "eyes_6", img: "resources/customisation/limezu/Eyes_6.png"},
    "eyes_7": {name: "eyes_7", img: "resources/customisation/limezu/Eyes_7_.png"},
};

export const HAIR_RESOURCES: BodyResourceDescriptionListInterface = {
    "hair_1_1": {name: "hair_1_1", img: "resources/customisation/limezu/Hairstyle_1_1.png"},
    "hair_2_1": {name: "hair_2_1", img: "resources/customisation/limezu/Hairstyle_2_1.png"},
    "hair_3_1": {name: "hair_3_1", img: "resources/customisation/limezu/Hairstyle_3_1.png"},
    "hair_4_1": {name: "hair_4_1", img: "resources/customisation/limezu/Hairstyle_4_1.png"},
    "hair_5_1": {name: "hair_5_1", img: "resources/customisation/limezu/Hairstyle_5_1.png"},
    "hair_6_1": {name: "hair_6_1", img: "resources/customisation/limezu/Hairstyle_6_1.png"},
    "hair_7_1": {name: "hair_7_1", img: "resources/customisation/limezu/Hairstyle_7_1.png"},
    "hair_8_1": {name: "hair_8_1", img: "resources/customisation/limezu/Hairstyle_8_1.png"},
    "hair_9_1": {name: "hair_9_1", img: "resources/customisation/limezu/Hairstyle_9_1.png"},
    "hair_10_1": {name: "hair_10_1", img: "resources/customisation/limezu/Hairstyle_10_1.png"},
    "hair_11_1": {name: "hair_11_1", img: "resources/customisation/limezu/Hairstyle_11_1.png"},
    "hair_12_1": {name: "hair_12_1", img: "resources/customisation/limezu/Hairstyle_12_1.png"},
    "hair_13_1": {name: "hair_13_1", img: "resources/customisation/limezu/Hairstyle_13_1.png"},
    "hair_14_1": {name: "hair_14_1", img: "resources/customisation/limezu/Hairstyle_14_1.png"},
    "hair_15_1": {name: "hair_15_1", img: "resources/customisation/limezu/Hairstyle_15_1.png"},
    "hair_16_1": {name: "hair_16_1", img: "resources/customisation/limezu/Hairstyle_16_1.png"},
    "hair_17_1": {name: "hair_17_1", img: "resources/customisation/limezu/Hairstyle_17_1.png"},
    "hair_18_1": {name: "hair_18_1", img: "resources/customisation/limezu/Hairstyle_18_1.png"},
    "hair_19_1": {name: "hair_19_1", img: "resources/customisation/limezu/Hairstyle_19_1.png"},
    "hair_20_1": {name: "hair_20_1", img: "resources/customisation/limezu/Hairstyle_20_1.png"},
    "hair_21_1": {name: "hair_21_1", img: "resources/customisation/limezu/Hairstyle_21_1.png"},
    "hair_22_1": {name: "hair_22_1", img: "resources/customisation/limezu/Hairstyle_22_1.png"},
    "hair_25_1": {name: "hair_25_1", img: "resources/customisation/limezu/Hairstyle_25_1.png"},
    "hair_26_1": {name: "hair_26_1", img: "resources/customisation/limezu/Hairstyle_26_1.png"},
    "hair_1_2": {name: "hair_1_2", img: "resources/customisation/limezu/Hairstyle_1_2.png"},
    "hair_2_2": {name: "hair_2_2", img: "resources/customisation/limezu/Hairstyle_2_2.png"},
    "hair_3_2": {name: "hair_3_2", img: "resources/customisation/limezu/Hairstyle_3_2.png"},
    "hair_4_2": {name: "hair_4_2", img: "resources/customisation/limezu/Hairstyle_4_2.png"},
    "hair_5_2": {name: "hair_5_2", img: "resources/customisation/limezu/Hairstyle_5_2.png"},
    "hair_6_2": {name: "hair_6_2", img: "resources/customisation/limezu/Hairstyle_6_2.png"},
    "hair_7_2": {name: "hair_7_2", img: "resources/customisation/limezu/Hairstyle_7_2.png"},
    "hair_8_2": {name: "hair_8_2", img: "resources/customisation/limezu/Hairstyle_8_2.png"},
    "hair_9_2": {name: "hair_9_2", img: "resources/customisation/limezu/Hairstyle_9_2.png"},
    "hair_10_2": {name: "hair_10_2", img: "resources/customisation/limezu/Hairstyle_10_2.png"},
    "hair_11_2": {name: "hair_11_2", img: "resources/customisation/limezu/Hairstyle_11_2.png"},
    "hair_12_2": {name: "hair_12_2", img: "resources/customisation/limezu/Hairstyle_12_2.png"},
    "hair_13_2": {name: "hair_13_2", img: "resources/customisation/limezu/Hairstyle_13_2.png"},
    "hair_14_2": {name: "hair_14_2", img: "resources/customisation/limezu/Hairstyle_14_2.png"},
    "hair_15_2": {name: "hair_15_2", img: "resources/customisation/limezu/Hairstyle_15_2.png"},
    "hair_16_2": {name: "hair_16_2", img: "resources/customisation/limezu/Hairstyle_16_2.png"},
    "hair_17_2": {name: "hair_17_2", img: "resources/customisation/limezu/Hairstyle_17_2.png"},
    "hair_18_2": {name: "hair_18_2", img: "resources/customisation/limezu/Hairstyle_18_2.png"},
    "hair_19_2": {name: "hair_19_2", img: "resources/customisation/limezu/Hairstyle_19_2.png"},
    "hair_20_2": {name: "hair_20_2", img: "resources/customisation/limezu/Hairstyle_20_2.png"},
    "hair_21_2": {name: "hair_21_2", img: "resources/customisation/limezu/Hairstyle_21_2.png"},
    "hair_22_2": {name: "hair_22_2", img: "resources/customisation/limezu/Hairstyle_22_2.png"},
    "hair_25_2": {name: "hair_25_2", img: "resources/customisation/limezu/Hairstyle_25_2.png"},
    "hair_26_2": {name: "hair_26_2", img: "resources/customisation/limezu/Hairstyle_26_2.png"},
    "hair_1_3": {name: "hair_1_3", img: "resources/customisation/limezu/Hairstyle_1_3.png"},
    "hair_2_3": {name: "hair_2_3", img: "resources/customisation/limezu/Hairstyle_2_3.png"},
    "hair_3_3": {name: "hair_3_3", img: "resources/customisation/limezu/Hairstyle_3_3.png"},
    "hair_4_3": {name: "hair_4_3", img: "resources/customisation/limezu/Hairstyle_4_3.png"},
    "hair_5_3": {name: "hair_5_3", img: "resources/customisation/limezu/Hairstyle_5_3.png"},
    "hair_6_3": {name: "hair_6_3", img: "resources/customisation/limezu/Hairstyle_6_3.png"},
    "hair_7_3": {name: "hair_7_3", img: "resources/customisation/limezu/Hairstyle_7_3.png"},
    "hair_8_3": {name: "hair_8_3", img: "resources/customisation/limezu/Hairstyle_8_3.png"},
    "hair_9_3": {name: "hair_9_3", img: "resources/customisation/limezu/Hairstyle_9_3.png"},
    "hair_10_3": {name: "hair_10_3", img: "resources/customisation/limezu/Hairstyle_10_3.png"},
    "hair_11_3": {name: "hair_11_3", img: "resources/customisation/limezu/Hairstyle_11_3.png"},
    "hair_12_3": {name: "hair_12_3", img: "resources/customisation/limezu/Hairstyle_12_3.png"},
    "hair_13_3": {name: "hair_13_3", img: "resources/customisation/limezu/Hairstyle_13_3.png"},
    "hair_14_3": {name: "hair_14_3", img: "resources/customisation/limezu/Hairstyle_14_3.png"},
    "hair_15_3": {name: "hair_15_3", img: "resources/customisation/limezu/Hairstyle_15_3.png"},
    "hair_16_3": {name: "hair_16_3", img: "resources/customisation/limezu/Hairstyle_16_3.png"},
    "hair_17_3": {name: "hair_17_3", img: "resources/customisation/limezu/Hairstyle_17_3.png"},
    "hair_18_3": {name: "hair_18_3", img: "resources/customisation/limezu/Hairstyle_18_3.png"},
    "hair_19_3": {name: "hair_19_3", img: "resources/customisation/limezu/Hairstyle_19_3.png"},
    "hair_20_3": {name: "hair_20_3", img: "resources/customisation/limezu/Hairstyle_20_3.png"},
    "hair_21_3": {name: "hair_21_3", img: "resources/customisation/limezu/Hairstyle_21_3.png"},
    "hair_22_3": {name: "hair_22_3", img: "resources/customisation/limezu/Hairstyle_22_3.png"},
    "hair_25_3": {name: "hair_25_3", img: "resources/customisation/limezu/Hairstyle_25_3.png"},
    "hair_26_3": {name: "hair_26_3", img: "resources/customisation/limezu/Hairstyle_26_3.png"},
    "hair_1_4": {name: "hair_1_4", img: "resources/customisation/limezu/Hairstyle_1_4.png"},
    "hair_2_4": {name: "hair_2_4", img: "resources/customisation/limezu/Hairstyle_2_4.png"},
    "hair_3_4": {name: "hair_3_4", img: "resources/customisation/limezu/Hairstyle_3_4.png"},
    "hair_4_4": {name: "hair_4_4", img: "resources/customisation/limezu/Hairstyle_4_4.png"},
    "hair_5_4": {name: "hair_5_4", img: "resources/customisation/limezu/Hairstyle_5_4.png"},
    "hair_6_4": {name: "hair_6_4", img: "resources/customisation/limezu/Hairstyle_6_4.png"},
    "hair_7_4": {name: "hair_7_4", img: "resources/customisation/limezu/Hairstyle_7_4.png"},
    "hair_8_4": {name: "hair_8_4", img: "resources/customisation/limezu/Hairstyle_8_4.png"},
    "hair_9_4": {name: "hair_9_4", img: "resources/customisation/limezu/Hairstyle_9_4.png"},
    "hair_10_4": {name: "hair_10_4", img: "resources/customisation/limezu/Hairstyle_10_4.png"},
    "hair_11_4": {name: "hair_11_4", img: "resources/customisation/limezu/Hairstyle_11_4.png"},
    "hair_12_4": {name: "hair_12_4", img: "resources/customisation/limezu/Hairstyle_12_4.png"},
    "hair_13_4": {name: "hair_13_4", img: "resources/customisation/limezu/Hairstyle_13_4.png"},
    "hair_14_4": {name: "hair_14_4", img: "resources/customisation/limezu/Hairstyle_14_4.png"},
    "hair_15_4": {name: "hair_15_4", img: "resources/customisation/limezu/Hairstyle_15_4.png"},
    "hair_16_4": {name: "hair_16_4", img: "resources/customisation/limezu/Hairstyle_16_4.png"},
    "hair_17_4": {name: "hair_17_4", img: "resources/customisation/limezu/Hairstyle_17_4.png"},
    "hair_18_4": {name: "hair_18_4", img: "resources/customisation/limezu/Hairstyle_18_4.png"},
    "hair_19_4": {name: "hair_19_4", img: "resources/customisation/limezu/Hairstyle_19_4.png"},
    "hair_20_4": {name: "hair_20_4", img: "resources/customisation/limezu/Hairstyle_20_4.png"},
    "hair_21_4": {name: "hair_21_4", img: "resources/customisation/limezu/Hairstyle_21_4.png"},
    "hair_22_4": {name: "hair_22_4", img: "resources/customisation/limezu/Hairstyle_22_4.png"},
    "hair_25_4": {name: "hair_25_4", img: "resources/customisation/limezu/Hairstyle_25_4.png"},
    "hair_26_4": {name: "hair_26_4", img: "resources/customisation/limezu/Hairstyle_26_4.png"},
    "hair_1_5": {name: "hair_1_5", img: "resources/customisation/limezu/Hairstyle_1_5.png"},
    "hair_2_5": {name: "hair_2_5", img: "resources/customisation/limezu/Hairstyle_2_5.png"},
    "hair_3_5": {name: "hair_3_5", img: "resources/customisation/limezu/Hairstyle_3_5.png"},
    "hair_4_5": {name: "hair_4_5", img: "resources/customisation/limezu/Hairstyle_4_5.png"},
    "hair_5_5": {name: "hair_5_5", img: "resources/customisation/limezu/Hairstyle_5_5.png"},
    "hair_6_5": {name: "hair_6_5", img: "resources/customisation/limezu/Hairstyle_6_5.png"},
    "hair_7_5": {name: "hair_7_5", img: "resources/customisation/limezu/Hairstyle_7_5.png"},
    "hair_8_5": {name: "hair_8_5", img: "resources/customisation/limezu/Hairstyle_8_5.png"},
    "hair_9_5": {name: "hair_9_5", img: "resources/customisation/limezu/Hairstyle_9_5.png"},
    "hair_10_5": {name: "hair_10_5", img: "resources/customisation/limezu/Hairstyle_10_5.png"},
    "hair_11_5": {name: "hair_11_5", img: "resources/customisation/limezu/Hairstyle_11_5.png"},
    "hair_12_5": {name: "hair_12_5", img: "resources/customisation/limezu/Hairstyle_12_5.png"},
    "hair_13_5": {name: "hair_13_5", img: "resources/customisation/limezu/Hairstyle_13_5.png"},
    "hair_14_5": {name: "hair_14_5", img: "resources/customisation/limezu/Hairstyle_14_5.png"},
    "hair_15_5": {name: "hair_15_5", img: "resources/customisation/limezu/Hairstyle_15_5.png"},
    "hair_16_5": {name: "hair_16_5", img: "resources/customisation/limezu/Hairstyle_16_5.png"},
    "hair_17_5": {name: "hair_17_5", img: "resources/customisation/limezu/Hairstyle_17_5.png"},
    "hair_18_5": {name: "hair_18_5", img: "resources/customisation/limezu/Hairstyle_18_5.png"},
    "hair_19_5": {name: "hair_19_5", img: "resources/customisation/limezu/Hairstyle_19_5.png"},
    "hair_20_5": {name: "hair_20_5", img: "resources/customisation/limezu/Hairstyle_20_5.png"},
    "hair_21_5": {name: "hair_21_5", img: "resources/customisation/limezu/Hairstyle_21_5.png"},
    "hair_22_5": {name: "hair_22_5", img: "resources/customisation/limezu/Hairstyle_22_5.png"},
    "hair_25_5": {name: "hair_25_5", img: "resources/customisation/limezu/Hairstyle_25_5.png"},
    "hair_26_5": {name: "hair_26_5", img: "resources/customisation/limezu/Hairstyle_26_5.png"},
    "hair_1_6": {name: "hair_1_6", img: "resources/customisation/limezu/Hairstyle_1_6.png"},
    "hair_2_6": {name: "hair_2_6", img: "resources/customisation/limezu/Hairstyle_2_6.png"},
    "hair_3_6": {name: "hair_3_6", img: "resources/customisation/limezu/Hairstyle_3_6.png"},
    "hair_4_6": {name: "hair_4_6", img: "resources/customisation/limezu/Hairstyle_4_6.png"},
    "hair_5_6": {name: "hair_5_6", img: "resources/customisation/limezu/Hairstyle_5_6.png"},
    "hair_6_6": {name: "hair_6_6", img: "resources/customisation/limezu/Hairstyle_6_6.png"},
    "hair_7_6": {name: "hair_7_6", img: "resources/customisation/limezu/Hairstyle_7_6.png"},
    "hair_8_6": {name: "hair_8_6", img: "resources/customisation/limezu/Hairstyle_8_6.png"},
    "hair_9_6": {name: "hair_9_6", img: "resources/customisation/limezu/Hairstyle_9_6.png"},
    "hair_10_6": {name: "hair_10_6", img: "resources/customisation/limezu/Hairstyle_10_6.png"},
    "hair_11_6": {name: "hair_11_6", img: "resources/customisation/limezu/Hairstyle_11_6.png"},
    "hair_12_6": {name: "hair_12_6", img: "resources/customisation/limezu/Hairstyle_12_6.png"},
    "hair_13_6": {name: "hair_13_6", img: "resources/customisation/limezu/Hairstyle_13_6.png"},
    "hair_14_6": {name: "hair_14_6", img: "resources/customisation/limezu/Hairstyle_14_6.png"},
    "hair_15_6": {name: "hair_15_6", img: "resources/customisation/limezu/Hairstyle_15_6.png"},
    "hair_16_6": {name: "hair_16_6", img: "resources/customisation/limezu/Hairstyle_16_6.png"},
    "hair_17_6": {name: "hair_17_6", img: "resources/customisation/limezu/Hairstyle_17_6.png"},
    "hair_18_6": {name: "hair_18_6", img: "resources/customisation/limezu/Hairstyle_18_6.png"},
    "hair_19_6": {name: "hair_19_6", img: "resources/customisation/limezu/Hairstyle_19_6.png"},
    "hair_20_6": {name: "hair_20_6", img: "resources/customisation/limezu/Hairstyle_20_6.png"},
    "hair_21_6": {name: "hair_21_6", img: "resources/customisation/limezu/Hairstyle_21_6.png"},
    "hair_22_6": {name: "hair_22_6", img: "resources/customisation/limezu/Hairstyle_22_6.png"},
    "hair_25_6": {name: "hair_25_6", img: "resources/customisation/limezu/Hairstyle_25_6.png"},
    "hair_26_6": {name: "hair_26_6", img: "resources/customisation/limezu/Hairstyle_26_6.png"},
    "hair_1_7": {name: "hair_1_7", img: "resources/customisation/limezu/Hairstyle_1_7.png"},
    "hair_2_7": {name: "hair_2_7", img: "resources/customisation/limezu/Hairstyle_2_7.png"},
    "hair_3_7": {name: "hair_3_7", img: "resources/customisation/limezu/Hairstyle_3_7.png"},
    "hair_4_7": {name: "hair_4_7", img: "resources/customisation/limezu/Hairstyle_4_7.png"},
    "hair_5_7": {name: "hair_5_7", img: "resources/customisation/limezu/Hairstyle_5_7.png"},
    "hair_6_7": {name: "hair_6_7", img: "resources/customisation/limezu/Hairstyle_6_7.png"},
    "hair_7_7": {name: "hair_7_7", img: "resources/customisation/limezu/Hairstyle_7_7.png"},
    "hair_8_7": {name: "hair_8_7", img: "resources/customisation/limezu/Hairstyle_8_7.png"},
    "hair_9_7": {name: "hair_9_7", img: "resources/customisation/limezu/Hairstyle_9_7.png"},
    "hair_10_7": {name: "hair_10_7", img: "resources/customisation/limezu/Hairstyle_10_7.png"},
    "hair_11_7": {name: "hair_11_7", img: "resources/customisation/limezu/Hairstyle_11_7.png"},
    "hair_12_7": {name: "hair_12_7", img: "resources/customisation/limezu/Hairstyle_12_7.png"},
    "hair_13_7": {name: "hair_13_7", img: "resources/customisation/limezu/Hairstyle_13_7.png"},
    "hair_14_7": {name: "hair_14_7", img: "resources/customisation/limezu/Hairstyle_14_7.png"},
    "hair_15_7": {name: "hair_15_7", img: "resources/customisation/limezu/Hairstyle_15_7.png"},
    "hair_16_7": {name: "hair_16_7", img: "resources/customisation/limezu/Hairstyle_16_7.png"},
    "hair_17_7": {name: "hair_17_7", img: "resources/customisation/limezu/Hairstyle_17_7.png"},
    "hair_18_7": {name: "hair_18_7", img: "resources/customisation/limezu/Hairstyle_18_7.png"},
    "hair_19_7": {name: "hair_19_7", img: "resources/customisation/limezu/Hairstyle_19_7.png"},
    "hair_20_7": {name: "hair_20_7", img: "resources/customisation/limezu/Hairstyle_20_7.png"},
    "hair_21_7": {name: "hair_21_7", img: "resources/customisation/limezu/Hairstyle_21_7.png"},
    "hair_22_7": {name: "hair_22_7", img: "resources/customisation/limezu/Hairstyle_22_7.png"},
    "hair_25_7": {name: "hair_25_7", img: "resources/customisation/limezu/Hairstyle_25_7.png"},
    "hair_26_7": {name: "hair_26_7", img: "resources/customisation/limezu/Hairstyle_26_7.png"},
};

export const CLOTHES_RESOURCES: BodyResourceDescriptionListInterface = {
    "outfit_01": {name: "outfit_01", img: "resources/customisation/limezu/Outfit_10.png"},
    "outfit_02": {name: "outfit_02", img: "resources/customisation/limezu/Outfit_11.png"},
    "outfit_03": {name: "outfit_03", img: "resources/customisation/limezu/Outfit_12_Doctor.png"},
    "outfit_04": {name: "outfit_04", img: "resources/customisation/limezu/Outfit_13.png"},
    "outfit_05": {name: "outfit_05", img: "resources/customisation/limezu/Outfit_14.png"},
    "outfit_06": {name: "outfit_06", img: "resources/customisation/limezu/Outfit_15.png"},
    "outfit_07": {name: "outfit_07", img: "resources/customisation/limezu/Outfit_16.png"},
    "outfit_08": {name: "outfit_08", img: "resources/customisation/limezu/Outfit_17_Nurse.png"},
    "outfit_09": {name: "outfit_09", img: "resources/customisation/limezu/Outfit_18.png"},
    "outfit_10": {name: "outfit_10", img: "resources/customisation/limezu/Outfit_19.png"},
    "outfit_11": {name: "outfit_11", img: "resources/customisation/limezu/Outfit_1.png"},
    "outfit_12": {name: "outfit_12", img: "resources/customisation/limezu/Outfit_20.png"},
    "outfit_13": {name: "outfit_13", img: "resources/customisation/limezu/Outfit_21.png"},
    "outfit_14": {name: "outfit_14", img: "resources/customisation/limezu/Outfit_22.png"},
    "outfit_15": {name: "outfit_15", img: "resources/customisation/limezu/Outfit_2.png"},
    "outfit_16": {name: "outfit_16", img: "resources/customisation/limezu/Outfit_3.png"},
    "outfit_17": {name: "outfit_17", img: "resources/customisation/limezu/Outfit_4.png"},
    "outfit_18": {name: "outfit_18", img: "resources/customisation/limezu/Outfit_5.png"},
    "outfit_19": {name: "outfit_19", img: "resources/customisation/limezu/Outfit_6_Butcher.png"},
    "outfit_20": {name: "outfit_20", img: "resources/customisation/limezu/Outfit_7_Chef.png"},
    "outfit_21": {name: "outfit_21", img: "resources/customisation/limezu/Outfit_8.png"},
    "outfit_22": {name: "outfit_22", img: "resources/customisation/limezu/Outfit_9.png"},
};

export const HATS_RESOURCES: BodyResourceDescriptionListInterface = {
    "hat_0": {name: "etc_0", img: "resources/customisation/limezu/empty.png"},
    "hat_1": {name: "etc_3", img: "resources/customisation/limezu/Hat_1_Chef.png"},
    "hat_2": {name: "etc_4", img: "resources/customisation/limezu/Head_1_Bolt.png"},
};

export const ACCESSORIES_RESOURCES: BodyResourceDescriptionListInterface = {
    "etc_0": {name: "etc_0", img: "resources/customisation/limezu/empty.png"},
    "etc_1": {name: "etc_1", img: "resources/customisation/limezu/Glasses_1_.png"},
    "etc_2": {name: "etc_2", img: "resources/customisation/limezu/Gloves_1_Nurse.png"},
};

export const LAYERS: BodyResourceDescriptionListInterface[] = [
    COLOR_RESOURCES,
    EYES_RESOURCES,
    HAIR_RESOURCES,
    CLOTHES_RESOURCES,
    HATS_RESOURCES,
    ACCESSORIES_RESOURCES
];

export const OBJECTS: BodyResourceDescriptionInterface[] = [
    {name:'teleportation', img:'resources/objects/teleportation.png'},
];
